development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: decider_development
  pool: 5
  username: root
  password: root
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: decider_test
  pool: 5
  username: root
  password: root
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: decider_prduction
  pool: 5
  username: ENV['DECIDER_DB_USERNAME']
  password: ENV['DECIDER_DB_PASSWORD']
