development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nayati_development
  pool: 5
  username: root
  password: root
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nayati_test
  pool: 5
  username: root
  password: root
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nayati_prduction
  pool: 5
  username: ENV['DECIDER_DB_USERNAME']
  password: ENV['DECIDER_DB_PASSWORD']
